name: Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '13 6 * * *'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: docker
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: ✨ Setup Hugo
        env:
          HUGO_VERSION: 0.135.0
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          mv hugo /usr/local/bin          
      - name: 🛠️ Build
        run: hugo
      - name: Install Rsync and SSH
        run: |
          apt-get update -y
          apt-get install -y rsync openssh-client
      - name: 🔐 Create Key File
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa
      - name: 🔑 Populate Key
        run: echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
      - name: 🚀 Upload
        run: rsync -rlp --stats --delete -e 'ssh -o StrictHostKeyChecking=no' public/ webdeploy@192.168.14.1:/srv/shows/
